# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zuck 3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "zuck"
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jannis Hermanns"]
  s.date = "2016-01-15"
  s.description = "This gem allows to easily access facebook's ads api in ruby. See https://developers.facebook.com/docs/reference/ads-api/"
  s.email = "jannis@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "console",
    "lib/zuck.rb",
    "lib/zuck/facebook/ad.rb",
    "lib/zuck/facebook/ad_account.rb",
    "lib/zuck/facebook/ad_set.rb",
    "lib/zuck/facebook/campaign.rb",
    "lib/zuck/fb_object.rb",
    "lib/zuck/fb_object/dsl.rb",
    "lib/zuck/fb_object/error.rb",
    "lib/zuck/fb_object/hash_delegator.rb",
    "lib/zuck/fb_object/helpers.rb",
    "lib/zuck/fb_object/read.rb",
    "lib/zuck/fb_object/read_only.rb",
    "lib/zuck/fb_object/write.rb",
    "lib/zuck/helpers.rb",
    "lib/zuck/koala/koala_methods.rb",
    "zuck.gemspec"
  ]
  s.homepage = "http://github.com/jayniz/zuck"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Ruby adapter to facebook's ad api"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<koala>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<koala>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<koala>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

