# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zuck 3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name        = 'zuck'
  s.version     = '3.0.0'
  s.platform    = Gem::Platform::RUBY
  s.licenses    = ['MIT']
  s.authors     = ['Chris Estreich']
  s.email       = 'cestreich@gmail.com'
  s.homepage    = 'http://github.com/cte/zuck'
  s.summary     = "Ruby adapter to Facebook's Marketing API."
  s.description = "This gem allows to easily access Facebook's Marketing API in ruby. See https://developers.facebook.com/docs/reference/ads-api/"

  s.extra_rdoc_files = ['README.markdown']

  s.required_ruby_version = '~> 2.0'

  s.add_dependency 'bundler'
  s.add_dependency 'koala'
  s.add_dependency 'activesupport'
  s.add_dependency 'pry'
  s.add_dependency 'httparty'
  s.add_dependency 'httmultiparty'

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map { |f| File.basename(f) }
  s.require_paths = ['lib']

end
